### ISSUE TITLE
puppeteer error?

### ISSUE THREAD

**Issue by erentar** [snobu/destreamer#101]
`> ./destreamer.sh -i "https://web.microsoftstream.com/video/01d90915-8697-4f0f-846f-4f8a8de8cb20"`
```
Using ffmpeg version 4.2.2-1+b1 Copyright (c) 2000-2019 the FFmpeg developers

.token_cache not found.

Launching headless Chrome to perform the OpenID Connect dance...
Error: Failed to launch the browser process!
[73814:73814:0427/160432.224159:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x561c1cc41219 base::debug::CollectStackTrace()
#1 0x561c1cba5363 base::debug::StackTrace::StackTrace()
#2 0x561c1cbb7195 logging::LogMessage::~LogMessage()
#3 0x561c1e43300e service_manager::ZygoteHostImpl::Init()
#4 0x561c1c7aef27 content::ContentMainRunnerImpl::Initialize()
#5 0x561c1c7fdafa service_manager::Main()
#6 0x561c1c7ad501 content::ContentMain()
#7 0x561c1a371aae ChromeMain
#8 0x7fac9f01ae0b __libc_start_main
#9 0x561c1a3718ea _start

Received signal 6
#0 0x561c1cc41219 base::debug::CollectStackTrace()
#1 0x561c1cba5363 base::debug::StackTrace::StackTrace()
#2 0x561c1cc40d61 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7faca114c110 <unknown>
#4 0x7fac9f02f761 gsignal
#5 0x7fac9f01955b abort
#6 0x561c1cc3fb65 base::debug::BreakDebugger()
#7 0x561c1cbb7634 logging::LogMessage::~LogMessage()
#8 0x561c1e43300e service_manager::ZygoteHostImpl::Init()
#9 0x561c1c7aef27 content::ContentMainRunnerImpl::Initialize()
#10 0x561c1c7fdafa service_manager::Main()
#11 0x561c1c7ad501 content::ContentMain()
#12 0x561c1a371aae ChromeMain
#13 0x7fac9f01ae0b __libc_start_main
#14 0x561c1a3718ea _start
  r8: 0000000000000000  r9: 00007fff4e820c80 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007fff4e821f48 r13: 00007fff4e820f20 r14: 00007fff4e821f50 r15: aaaaaaaaaaaaaaaa
  di: 0000000000000002  si: 00007fff4e820c80  bp: 00007fff4e820ed0  bx: 00007fac9dacfd40
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fac9f02f761  sp: 00007fff4e820c80
  ip: 00007fac9f02f761 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/user/git/destreamer/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.helper.addEventListener (/home/user/git/destreamer/node_modules/puppeteer/lib/Launcher.js:739:50)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)


Unhandled error!
Timeout or fatal error, please check your downloads directory and try again 
```
built with instructions:
```
sudo apt install nodejs npm -y
git clone https://github.com/snobu/destreamer
npm install
npm run build
```
(video id is fake btw)

**Comment by snobu** [comment]
Are you on Linux? Make sure you're not running as root, looks like your Kernel is a little stale you may want to upgrade.

Alternatively try running Chromium without the sandbox, add `--no-sandbox` to this array:
https://github.com/snobu/destreamer/blob/master/src/destreamer.ts#L57

--

**Comment by erentar** [comment]
uname -a: `Linux 5.5.0-2-amd64 #1 SMP Debian 5.5.17-1 (2020-04-15) x86_64 GNU/Linux`
not running as root
will try rebuilding with --no-sandbox, will report back

**Comment by erentar** [comment]
Line 57 on src/dstreamer.ts:
`57         args: ['--disable-dev-shm-usage --no-sandbox']`
rebuilt with same instructions, still get the same output

**Comment by erentar** [comment]
nvm my bad, probably should do 
` args: ['--disable-dev-shm-usage',  '--no-sandbox']`

**Comment by erentar** [comment]
yeah, it works now
Thanks!
