### ISSUE TITLE
Invalid Token Error

### ISSUE THREAD

**Issue by deepaksmgit** [snobu/destreamer#126]
Hi Thanks for creating this utility , however i am not able to run this tool , getting below error.
Can you please help ?

Using ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers

Error [InvalidTokenError]
    at Object.<anonymous> (/Users/deepakm/Tools/destreamer/node_modules/jwt-decode/lib/index.js:9:31)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/deepakm/Tools/destreamer/build/src/TokenCache.js:15:38)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10) {
  message: 'Invalid token specified'
}

Unhandled error!
Timeout or fatal error, please check your downloads directory and try again

**Comment by snobu** [comment]
Well that's strange, look like the access token you get from your tenant is not a JWT token. Can you post the first 20 characters or so from the AccessToken property found inside the file .token_cache?

Please do not post the full value as it may reveal personal information.

**Comment by tulgartarik** [comment]
> Hi Thanks for creating this utility , however i am not able to run this tool , getting below error.
> Can you please help ?
> 
> Using ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
> 
> Error [InvalidTokenError]
> at Object. (/Users/deepakm/Tools/destreamer/node_modules/jwt-decode/lib/index.js:9:31)
> at Module._compile (internal/modules/cjs/loader.js:1176:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
> at Module.load (internal/modules/cjs/loader.js:1040:32)
> at Function.Module._load (internal/modules/cjs/loader.js:929:14)
> at Module.require (internal/modules/cjs/loader.js:1080:19)
> at require (internal/modules/cjs/helpers.js:72:18)
> at Object. (/Users/deepakm/Tools/destreamer/build/src/TokenCache.js:15:38)
> at Module._compile (internal/modules/cjs/loader.js:1176:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10) {
> message: 'Invalid token specified'
> }
> 
> Unhandled error!
> Timeout or fatal error, please check your downloads directory and try again

https://nodejs.org/it/download/
did you install nodejs?

**Comment by snobu** [comment]
@deepaksmgit Still unable to login?

**Comment by lukaarma** [comment]
Closing this due to inactivity
@deepaksmgit reopen this if you need more help
