### ISSUE TITLE
Error: Parse Error: Header overflow

### ISSUE THREAD

**Issue by kichappa** [snobu/destreamer#129]
I ran this:
```
PS D:\somewhere\destreamer-win-64> ./destreamer.exe` -i 
"https://web.microsoftstream.com/video/some_code" -u "user@email.com" -v
```
But, I get the following error:

```
Using ffmpeg version git-2020-05-01-39fb1e9 Copyright (c) 2000-2020 the FFmpeg developers

Username: user@email.com
Video URLs:
[
  'https://web.microsoftstream.com/video/some_code'
]

Access token still good for 52 minutes.

Video GUIDs:
[ 'some_code' ]
Fetching metadata...
Calling https://jpea-1.api.microsoftstream.com/api/videos/some_code?api-version=1.4-private
[ 'videos' ]

Downloading Video: Japanese Language Ⅰ-Week 1
<image preview of the video, which is legit>

Spawning ffmpeg with access token and HLS URL. This may take a few seconds...
Error: Parse Error: Header overflow
    at TLSSocket.socketOnData (_http_client.js:479:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at TLSSocket.Readable.push (_stream_readable.js:214:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
  bytesParsed: 8358,
  code: 'HPE_HEADER_OVERFLOW',
  reason: 'Header overflow',
  rawPacket: <Buffer 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d 0a 43 61 63 68 65 2d 43 6f 6e 74 72 6f 6c 3a 20 6e 6f 2d 63 61 63 68 65 0d 0a 50 72 61 67 6d 61 3a 20 ... 8450 more bytes>,
  config: {
    url: 'https://jpea-1.api.microsoftstream.com/api/refreshtoken?api-version=1.4-private',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      Authorization: 'never_mind_me',
      'User-Agent': 'axios/0.19.2'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      errored: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'https:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/api/refreshtoken?api-version=1.4-private',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'jpea-1.api.microsoftstream.com',
      port: null,
      nativeProtocols: [Object],
      pathname: '/api/refreshtoken',
      search: '?api-version=1.4-private'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /api/refreshtoken?api-version=1.4-private HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Authorization: never_mind_me\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Host: jpea-1.api.microsoftstream.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/refreshtoken?api-version=1.4-private',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://jpea-1.api.microsoftstream.com/api/refreshtoken?api-version=1.4-private',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function (anonymous)]
}


Unhandled error!
Timeout or fatal error, please check your downloads directory and try again
```

**Comment by snobu** [comment]
Please use Node >v10 and launch via the cmd or ps1 scripts as the README shows.

**Comment by kichappa** [comment]
> Please use Node >v10 and launch via the cmd or ps1 scripts as the README shows.

Okay, I might have used [this](https://drive.google.com/uc?id=1j0X69xWtg3inshv9LsRqh4mvjqt7YcMk&export=download). 

Although, when I used cmd, I got the following once:
```
ffmpeg returned an error: https://jpea-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackurl=https://5yddjurlgquueiseguafqasvtg-jpea.streaming.media.azure.net/3eb3cade-ee03-4c92-af1c-d13b283d21e6/1-gpxcvroz2ydpaylmbedebkkfug.ism/manifest(format=m3u8-aapl): Unknown error



Unknown FFmpeg error
```

I'm not sure why, but adding a `-v` to the input solved it.

**Comment by snobu** [comment]
It's an intermittent problem with the API endpoint we're calling. I've added a retry policy but that code isn't pushed yet. Will be fixed shortly. If you get that error again just retry a few more times.
