### ISSUE TITLE
Administrator view 

### ISSUE THREAD

**Issue by belasor** [snobu/destreamer#147]
Hey everyone,

I need to download around 40 Videos from a user. I can access all the videos as a admin, however when I want to download them with my account through destreamer I´m getting an error message.

Downloading a video from my uploads is no problem.

> Unhandled error!
Timeout or fatal error, please check your downloads directory and try again

Is that currently not support?

**Comment by snobu** [comment]
Can you check if you get more error detail if you pass `-v`? If you can watch a video in your browser, then destreamer should be able to download it if you log in with the same credentials.

**Comment by belasor** [comment]
Sure, I just tried it again, and it is not working

> { Error: Request failed with status code 403
    at createError (C:\Users\c\Desktop\Streamdownloader\destreamer\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\c\Desktop\Streamdownloader\destreamer\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\c\Desktop\Streamdownloader\destreamer\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  config:
   { url:
      'videos/e4c4d471-1596-442e-adc6-dcc918eb383f?api-version=1.4-private',
     method: 'get',
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'destreamer/2.0 (Hammer of Dawn)',
        Authorization:
         'Bearer 
     baseURL: 'https://euwe-1.api.microsoftstream.com/api/',
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     timeout: 7000,
     adapter: [Function: httpAdapter],
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     'axios-retry': { retryCount: 0, lastRequestTime: 1590672776764 },
     data: undefined },
  request:
   ClientRequest {
     _events:
      [Object: null prototype] {
        socket: [Array],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Array],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'euwe-1.api.microsoftstream.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'euwe-1.api.microsoftstream.com',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        timeout: 7000,
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 40,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]:
         Timeout {
           _called: false,
           _idleTimeout: 7000,
           _idlePrev: [TimersList],
           _idleNext: [TimersList],
           _idleStart: 2067,
           _onTimeout: [Function: bound ],
           _timerArgs: undefined,
           _repeat: null,
           _destroyed: false,
           [Symbol(unrefed)]: true,
           [Symbol(asyncId)]: 49,
           [Symbol(triggerId)]: 47 },
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'euwe-1.api.microsoftstream.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: null,
        _host: 'euwe-1.api.microsoftstream.com',
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        timeout: 7000,
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 40,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]:
         Timeout {
           _called: false,
           _idleTimeout: 7000,
           _idlePrev: [TimersList],
           _idleNext: [TimersList],
           _idleStart: 2067,
           _onTimeout: [Function: bound ],
           _timerArgs: undefined,
           _repeat: null,
           _destroyed: false,
           [Symbol(unrefed)]: true,
           [Symbol(asyncId)]: 49,
           [Symbol(triggerId)]: 47 },
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     _header:
      'GET /api/videos/e4c4d471-1596-442e-adc6-dcc918eb383f?api-version=1.4-private HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: destreamer/2.0 (Hammer of Dawn)\r\nAuthorization: Bearer \r\nHost: euwe-1.api.microsoftstream.com\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path:
      '/api/videos/e4c4d471-1596-442e-adc6-dcc918eb383f?api-version=1.4-private',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [TLSSocket],
        connection: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 403,
        statusMessage: 'Forbidden',
        client: [TLSSocket],
        _consuming: false,
        _dumped: false,
        req: [Circular],
        responseUrl:
         'https://euwe-1.api.microsoftstream.com/api/videos/e4c4d471-1596-442e-adc6-dcc918eb383f?api-version=1.4-private',
        redirects: [] },
     aborted: undefined,
     timeoutCb: [Function: emitRequestTimeout],
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl:
         'https://euwe-1.api.microsoftstream.com/api/videos/e4c4d471-1596-442e-adc6-dcc918eb383f?api-version=1.4-private' },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] {
        accept: [Array],
        'user-agent': [Array],
        authorization: [Array],
        host: [Array] } },
  response:
   { status: 403,
     statusText: 'Forbidden',
     headers:
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-length': '133',
        'content-type': 'application/json; charset=utf-8',
        'content-language': 'en',
        expires: '-1',
        'x-ms-request-id': 'c6f8df4a-3c4c-4340-a247-a2fdaec09bff',
        'access-control-expose-headers': 'x-ms-request-id',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        date: 'Thu, 28 May 2020 13:32:57 GMT',
        connection: 'close' },
     config:
      { url:
         'videos/e4c4d471-1596-442e-adc6-dcc918eb383f?api-version=1.4-private',
        method: 'get',
        headers: [Object],
        baseURL: 'https://euwe-1.api.microsoftstream.com/api/',
        transformRequest: [Array],
        transformResponse: [Array],
        timeout: 7000,
        adapter: [Function: httpAdapter],
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        'axios-retry': [Object],
        data: undefined },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'GET /api/videos/e4c4d471-1596-442e-adc6-dcc918eb383f?api-version=1.4-private HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: destreamer/2.0 (Hammer of Dawn)\r\nAuthorization: Host: euwe-1.api.microsoftstream.com\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path:
         '/api/videos/e4c4d471-1596-442e-adc6-dcc918eb383f?api-version=1.4-private',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: [Function: emitRequestTimeout],
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     data: { error: [Object] } },
  isAxiosError: true,
  toJSON: [Function] }


Unhandled error!
Timeout or fatal error, please check your downloads directory and try again

**Comment by snobu** [comment]
That's a `403 Forbidden` HTTP response coming back from the MS Stream API. Destreamer won't be able to download that video.

**Comment by belasor** [comment]
Yeah I know, that is why I'm asking the question.

I'm accessing the video as Admin, so I can see the videos and also play the videos from other users. 

The downloading is working fine, when I'm using the credentials of the user, but as a admin I'm receiving the error above.

**Comment by lukaarma** [comment]
It may be that as an Admin there is a slightly different API approach that we don't know of @snobu?
I'll see if I can upload something and take a look

**Comment by bruno-telstar** [comment]
Hi everyone.

I have the same issue here. As a Global Admin, I wan to download all videos from all users, but I get the 403 Forbidden. But when I log on to Stream Website with this global admin user, I am able to access and download all videos.

If someone have any updates related to this issue, please let me know.

Best regards,

Bruno.

**Comment by lukaarma** [comment]
I found out I can upload videos too!
I'll try to reproduce the issue and I'll see if I can come up with something @bruno-telstar 

Stay tuned

**Comment by flamingghost** [comment]
For a workaround, as an Admin you can download videos already through the webpage under the video options.

**Comment by syakirazmi** [comment]
> For a workaround, as an Admin you can download videos already through the webpage under the video options.
yeah, but the problem is, the method is quite slow. We all uses destreamer because it is faster than the manual way
