### ISSUE TITLE
Unhandled error Timeout or fatal error

### ISSUE THREAD

**Issue by ewmartinez** [snobu/destreamer#163]
I have been trying to download from a WSL Ubuntu installation. 
After load chromium browser it display a blank windows, then the browser close:

This is the output
./destreamer.sh -i "https://web.microsoftstream.com/video/b85643de-XXXX-XXXX-ba16-63c45f40b476" -v
Using ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers

Video URLs:
[ 'https://web.microsoftstream.com/video/b85643de-XXXX-XXXX-ba16-63c45f40b476' ]
.token_cache not found.

Launching headless Chrome to perform the OpenID Connect dance...
Navigating to login page...
Error: Page crashed!
    at Page._onTargetCrashed (/home/user01/dev/destreamer/node_modules/puppeteer/lib/Page.js:213:24)
    at CDPSession.Page.client.on.event (/home/user01/dev/destreamer/node_modules/puppeteer/lib/Page.js:122:56)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
    at CDPSession._onMessage (/home/user01/dev/destreamer/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/home/user01/dev/destreamer/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocketTransport._ws.addEventListener.event (/home/user01/dev/destreamer/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/home/user01/dev/destreamer/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)

Unhandled error!
Timeout or fatal error, please check your downloads directory and try again 

--
The browser show the attached image
![error1](https://user-images.githubusercontent.com/6951562/85792513-9de37000-b701-11ea-959e-d38d36d42b7f.PNG)

**Comment by lukaarma** [comment]
You can try to take a look at [our readme](https://github.com/snobu/destreamer#limits-and-limitations) about WSL.

What I suggest is that you run Destreamer on Windows using powershell/cmd

**Comment by ewmartinez** [comment]
I'll try in power shell
Thank you

**Comment by ewmartinez** [comment]
It works on power shell..
Thank you
