### ISSUE TITLE
Chromium crashing on MacOS Mojave

### ISSUE THREAD

**Issue by sortedcord** [snobu/destreamer#172]
I have installed Node, NPM and ffmpeg and git correcty but when I try to download a video, it opens chromium and then it crashes and then I get an error saying that I need to check the downloads directory.

**Comment by sortedcord** [comment]
The error-
`
.token_cache not found.

Launching headless Chrome to perform the OpenID Connect dance...
Navigating to login page...
Error: net::ERR_NAME_NOT_RESOLVED at https://httphttps://web.microsoftstream.com/video/4dcee7f0-ca10-49d0-84cb-eb46cc8c1cdb
    at navigate (/Users/aditya/Documents/DeStreamer/destreamer/node_modules/puppeteer/lib/FrameManager.js:120:37)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async FrameManager.navigateFrame (/Users/aditya/Documents/DeStreamer/destreamer/node_modules/puppeteer/lib/FrameManager.js:94:17)
    at async Frame.goto (/Users/aditya/Documents/DeStreamer/destreamer/node_modules/puppeteer/lib/FrameManager.js:406:12)
    at async Page.goto (/Users/aditya/Documents/DeStreamer/destreamer/node_modules/puppeteer/lib/Page.js:672:12)
    at async DoInteractiveLogin (/Users/aditya/Documents/DeStreamer/destreamer/build/src/destreamer.js:55:5)
    at async main (/Users/aditya/Documents/DeStreamer/destreamer/build/src/destreamer.js:240:73)
  -- ASYNC --
    at Frame.<anonymous> (/Users/aditya/Documents/DeStreamer/destreamer/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/Users/aditya/Documents/DeStreamer/destreamer/node_modules/puppeteer/lib/Page.js:672:49)
    at Page.<anonymous> (/Users/aditya/Documents/DeStreamer/destreamer/node_modules/puppeteer/lib/helper.js:112:23)
    at DoInteractiveLogin (/Users/aditya/Documents/DeStreamer/destreamer/build/src/destreamer.js:55:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/Users/aditya/Documents/DeStreamer/destreamer/build/src/destreamer.js:240:73)


Unhandled error!
Timeout or fatal error, please check your downloads directory and try again 
`

**Comment by lukaarma** [comment]
There's something really wrong in the way it is parsing the URLs...could you paste here the command you use to launch it, censored if you prefer?

**Comment by sortedcord** [comment]
In order to launch it i got to the destreamer directory and then - ./destreamer -i "video_link"

**Comment by lukaarma** [comment]
> Error: net::ERR_NAME_NOT_RESOLVED at https://httphttps://web.microsoftstream.com/video/4dcee7f0-ca10-49d0-84cb-eb46cc8c1cdb

Knowing the way that Destreamer handles url sanitizing in the master branch and seeing what url Axios it's trying to fetch
tells me that you probably have an error on your input command (something like this ./destreamer -i "httphttps://web.microsoftstream.com/video/4dcee7f0-ca10-49d0-84cb-eb46cc8c1cdb")

Could you please check and make sure that the urls are in one of these 2 formats: 

- https://web.microsoftstream.com/video/4dcee7f0-ca10-49d0-84cb-eb46cc8c1cdb
- web.microsoftstream.com/video/4dcee7f0-ca10-49d0-84cb-eb46cc8c1cdb

**Comment by sortedcord** [comment]
Yes I am pretty sure its in this way. Moreover I have Windows (Bootcamp) on the same machine and I can download the same file using DeStreamer

**Comment by lukaarma** [comment]
So you are saying that using the same arguments both in Windows and on MacOS yield different results?

**Comment by sortedcord** [comment]
more or less..

**Comment by sortedcord** [comment]
Oh actually, I tried cloning it and building it in a different directory and it suprisingly worked!!! Thanks for the help!
