### ISSUE TITLE
[FATAL ERROR] Destreamer cannot run in an elevated (Administrator/root) shell.

### ISSUE THREAD

**Issue by roshanconnor123** [snobu/destreamer#200]
Hello there.
When I try to download one video I got this error
The command I used was
```
sh destreamer.sh -i "https://web.microsoftstream.com/video/c22686f1-e874ssdccsdc"
```
```
[FATAL ERROR] Destreamer cannot run in an elevated (Administrator/root) shell.
Please run in a regular, non-elevated window
```
How Can I fix this
Thank you
PS: I was running it in Ubuntu v18

**Comment by lukaarma** [comment]
As the error says you must not run this in an elevated shell.
Are you using root as the default user?

**Comment by roshanconnor123** [comment]
Yes
I am running it as root

**Comment by lukaarma** [comment]
Yes that would be a workaround

**Comment by roshanconnor123** [comment]
@lukaarma got this error now
```
[ERROR] Error: Failed to launch the browser process!
src/tcmalloc.cc:283] Attempt to free invalid pointer 0xa37a02b9a20 


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/content/destreamer/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.<anonymous> (/content/destreamer/node_modules/puppeteer/lib/Launcher.js:739:50)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
How can I fix this please
Thanks

**Comment by lukaarma** [comment]
If you try and run it again it keep happening?
If it's the case then please try to do a clean install in another folder and try again

**Comment by kryztiandt** [comment]
have you try run in "standard user" not in administrator user?

**Comment by snobu** [comment]
Closing. Just don't run as root.
