### ISSUE TITLE
Failed to launch the browser process! Unable to open X display.

### ISSUE THREAD

**Issue by Flwk** [snobu/destreamer#222]
Hello

I'm on Debian 64 bits

```
~/destreamer$ ./destreamer.sh -i "https://web.microsoftstream.com/video/XXXXXX" -o /home/XXX/XXX/

[WARNING] .token_cache not found.

Launching headless Chrome to perform the OpenID Connect dance...

[ERROR] Error: Failed to launch the browser process!
[25638:25638:0911/192128.402447:ERROR:browser_main_loop.cc(1512)] Unable to open X display.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/XXXX/destreamer/node_modules/puppeteer/lib/Launcher.js:750:14)
    at ChildProcess.<anonymous> (/home/XXXXX/destreamer/node_modules/puppeteer/lib/Launcher.js:740:61)
    at ChildProcess.emit (events.js:326:22)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)

```
I don't know how to solve this error

Thanks in advance

**Comment by snobu** [comment]
Are you running a graphical desktop? We spin up a browser window for login so XFCE/Gnome/KDE/whatever has an X Server is a must.

**Comment by Flwk** [comment]
Yeah i'm not running a graphical desktop, only by command line.

Do i have to install a graphical desktop or is there a way to do it with command line like in this [project](https://github.com/sup3rgiu/MStreamDownloader) ?

**Comment by snobu** [comment]
Sorry, no. You need X to run destreamer.
