### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by teodigg** [snobu/destreamer#224]
I get this error when trying to run destreamer on win 64

SyntaxError: missing ) after argument list
[90m    at wrapSafe (internal/modules/cjs/loader.js:1053:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1101:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:985:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:878:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m

**Comment by lukaarma** [comment]
Did you edit Destreamer code in any way?

**Comment by teodigg** [comment]
No

**Comment by lukaarma** [comment]
could you try to run `npm run build` and the launch it again?

**Comment by snobu** [comment]
Also check your Node version, should be 8.x or greater.

**Comment by lukaarma** [comment]
Was this solved @teodigg ?

**Comment by lukaarma** [comment]
Closing as inactive
