### ISSUE TITLE
about:blank

### ISSUE THREAD

**Issue by rostyclav999s** [snobu/destreamer#23]
Using youtube-dl version 2020.03.24
Using ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
Launching headless Chrome to perform the OpenID Connect dance...
Navigating to STS login page...
(node:936) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at /Users/rostyslavsalabay/destreamer-dev/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/rostyslavsalabay/destreamer-dev/node_modules/puppeteer/lib/Connection.js:182:12)
    at navigate (/Users/rostyslavsalabay/destreamer-dev/node_modules/puppeteer/lib/FrameManager.js:118:39)
    at FrameManager.navigateFrame (/Users/rostyslavsalabay/destreamer-dev/node_modules/puppeteer/lib/FrameManager.js:95:7)
    at Frame.goto (/Users/rostyslavsalabay/destreamer-dev/node_modules/puppeteer/lib/FrameManager.js:406:37)
    at Frame.<anonymous> (/Users/rostyslavsalabay/destreamer-dev/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.goto (/Users/rostyslavsalabay/destreamer-dev/node_modules/puppeteer/lib/Page.js:672:49)
    at Page.<anonymous> (/Users/rostyslavsalabay/destreamer-dev/node_modules/puppeteer/lib/helper.js:112:23)
    at rentVideoForLater (/Users/rostyslavsalabay/destreamer-dev/destreamer.js:70:16)
  -- ASYNC --
    at Frame.<anonymous> (/Users/rostyslavsalabay/destreamer-dev/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/Users/rostyslavsalabay/destreamer-dev/node_modules/puppeteer/lib/Page.js:672:49)
    at Page.<anonymous> (/Users/rostyslavsalabay/destreamer-dev/node_modules/puppeteer/lib/helper.js:112:23)
    at rentVideoForLater (/Users/rostyslavsalabay/destreamer-dev/destreamer.js:70:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:936) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:936) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
I'm running Mac OS Catalina, when I run the script the following error appears at the terminal and Chromium opens with about:blank window. This script worked fine for me on the same computer an hour ago

**Comment by snobu** [comment]
The relevant part of the error is `(Page.navigate): Cannot navigate to invalid URL`.

I don't really know what that means, since i can't reproduce it.

Can you post the video URL? I wonder if there'sny further clue in it.

**Comment by snobu** [comment]
Does your URL include the leading `https://`? That's a must, otherwise puppeteer may break with that exact error message.

**Comment by snobu** [comment]
Our code is now improved and should be way more deterministic in how it gets the video URL. Please git pull, transpile and try again. Feel free to reopen this issue if necessary.
