### ISSUE TITLE
Progress is stuck at 0%

### ISSUE THREAD

**Issue by mikolaje** [snobu/destreamer#282]
OS: MacOS

Launch command used: 
./destreamer.sh -u xxx@xxx.com  -i "https://web.microsoftstream.com/video/082235c2-2b4f6c5-9ee1-ed65f95036e7?list=watchlist" --verbose

![image](https://user-images.githubusercontent.com/11773334/99801443-00398300-2b71-11eb-858c-b0e4a52b5872.png)
<details>
<summary>Verbose  log</summary>
  
```
(node:11935) ExperimentalWarning: Package name self resolution is an experimental feature. This feature could change at any time

[VERBOSE] Using ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers

Username: xxx@xxx.com
Access token still good for 41 minutes.


[VERBOSE] Session and API info
	 API Gateway URL: https://aaea-1.api.microsoftstream.com/api/
	 API Gateway version: 1.4-private

Parsing video/group urls

[VERBOSE] List of GUIDs and corresponding output directory
	https://web.microsoftstream.com/video/082235c2-2b4f-46c5-9ee1-ed65f036e7 => videos

Fetching videos info...


Downloading Video: 2020 Fall Actual Lecture 1 Video Record 2


[VERBOSE] Extra video info
	 Video m3u8 playlist URL: https://aaea-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackurl=https://streamaaea1su021.azureedge.net/2971653f-0e32-4e08-a772-9de6062aa8/1-2crwnqiymwnzbgnghe6xsqde.ism/manifest(format=m3u8-aapl)
	 Video tumbnail URL: https://aaea-1-content.api.microsoftstream.com/api/thumbnails/2/babb24-a0ab-4bcd-8439-197a3e93a71b/MS0yY3J3bnFpeW13bnphNmJnbmdoZTZ4c3FkZV8xXzMyMHgxODAucG5n?validTill=2020-11-22T00%3a00%3a00.0000000Z&aadUserOId=3afe5c93-d068-40b2-ac270d66cdf6131&encoding=base64&api-version=1.4-private&signature=iK5FV0kDvUrY4oKF32UPI%2bpLty60YoyNsSqR%2fXKXA%3d
	 Video subtitle URL (may not exist): undefined
	 Video total chunks: 42.016666666666666

Spawning ffmpeg with access token and HLS URL. This may take a few seconds...
```
</details>

**Comment by mikolaje** [comment]
I suspect it was due to the terminal proxy network issue. After I added a proxy to my terminal and tried again, it turned out:
```
Fetching videos info...


[ERROR] Error: Input must be string
    at sanitize (/Users/me/opt/destreamer/node_modules/_sanitize-filename@1.6.3@sanitize-filename/index.js:41:11)
    at Object.module.exports [as default] (/Users/me/opt/destreamer/node_modules/_sanitize-filename@1.6.3@sanitize-filename/index.js:54:16)
    at Object.getVideoInfo (/Users/me/opt/destreamer/build/src/VideoUtils.js:59:44)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async downloadVideo (/Users/me/opt/destreamer/build/src/destreamer.js:103:50)
```

**Comment by snobu** [comment]
Just wondering if you managed to fix this on your own in the meantime.

**Comment by mikolaje** [comment]
> Just wondering if you managed to fix this on your own in the meantime.

hmm, sorry I'm not familiar with JS. I have no idea how to fix it.  I feel so appreciate if anyone can fix it. Thanks a lot.

**Comment by snobu** [comment]
I don't mean fix it in code, try destreamer on an internet connection that doesn't use a proxy.
We do not support downloading over a proxy.

**Comment by mikolaje** [comment]
> I don't mean fix it in code, what i mean is try destreamer on an internet connection that doesn't use a proxy.
> We do not support downloading over a proxy.

it seemed to be working on other network. it's probably due to the networking problem. Thanks for your reply. closed it.
