### ISSUE TITLE
Got HTTP code 403

### ISSUE THREAD

**Issue by nitpack** [snobu/destreamer#285]
it was just working great, downloaded 7 videos already today
but when I updated links in the txt file to download the next set of videos it gave me this:

Access token still good for 54 minutes.

Parsing input file
Fetching videos info...

[WARNING] Got HTTP code 403. Retrying request...

[ERROR] Error: Request failed with status code 403
    at createError (D:\others\destreamer-master\node_modules\axios\lib\core\createError.js:16:15)
    at settle (D:\others\destreamer-master\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (D:\others\destreamer-master\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

videos are still available and I have access to them, so what to do now?

UPDATE:
i managed to get another token and copy paste it to the ".token_cache", recieved a "HTTP code 401" this time.

UPDATE 2:
tried to reinstall 
got this error:
Fresh access token dropped into .token_cachen

Parsing input file
Fetching videos info...

[WARNING] Got HTTP code 403. Retrying request...
{
  error: {
    code: 'Forbidden',
    message: 'The authenticated user is not authorized to access this resource.'
  }
}

[ERROR] Error: Request failed with status code 403
    at createError (D:\others\destrmr\destreamer\node_modules\axios\lib\core\createError.js:16:15)
    at settle (D:\others\destrmr\destreamer\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (D:\others\destrmr\destreamer\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by antonvalletas** [comment]
Same happening to me right now.

**Comment by gymate-1** [comment]
I still have this issue with destreamer 2.2.

OS: MacOS 12.6
Launch command used: `./destreamer.sh -o /Users/gymate1/Downloads/ -u <username redacted by me> -f ffmpeg_MStream_list.txt -k -v`

<details>
<summary>Verbose log</summary>

```
[VERBOSE] Using ffmpeg version 5.1.1 Copyright (c) 2000-2022 the FFmpeg developers

Username: <redacted by me>

[WARNING] Access token has expired! 

Launching headless Chrome to perform the OpenID Connect dance...
Navigating to login page...
We are logged in.
Wrote access token to token cache.
At this point Chromium's job is done, shutting it down...

Fresh access token dropped into .token_cache 


[VERBOSE] Session and API info 
	 API Gateway URL: https://euwe-1.api.microsoftstream.com/api/
	 API Gateway version: 1.4-private

Parsing input file

[VERBOSE] List of GUIDs and corresponding output directory 
	<redacted by me>

Fetching videos info... 


[ERROR] Error: Request failed with status code 403
    at createError (/Users/gymate1/destreamer/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/gymate1/destreamer/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/gymate1/destreamer/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
</details>

**Comment by gy-mate** [comment]
@nitpack Could you please reopen this issue?

**Comment by nitpack** [comment]
> @nitpack Could you please reopen this issue?

done

**Comment by gy-mate** [comment]
@nitpack Thanks!
