### ISSUE TITLE
Cannot use my own browser

### ISSUE THREAD

**Issue by mcDandy** [snobu/destreamer#287]
I tryed running destreamer, but for whatever reason chrome starts only when I rename the executable. I tryed pointing it to chrome instalation directory. I did it exactly as in readme. changing line 52 of destreamer.ts to "executablePath: 'C:\Program Files\Google\Chrome\Application\chrome1.exe'," and building it.
OS: Windows 10 20H2

Launch command used:  .\destreamer.cmd -v -i [adress]

<details>
<summary>Verbose  log</summary>
  
```
[VERBOSE] Using ffmpeg version git-2020-07-29-cbb6ba2 Copyright (c) 2000-2020 the FFmpeg developers


[WARNING] Access token has expired!

Launching headless Chrome to perform the OpenID Connect dance...

[ERROR] Error: Failed to launch the browser process! spawn C:Program FilesGoogleChromeApplicationchrome1.exe ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (D:\Users\Daniel\Downloads\destreamer-master\node_modules\puppeteer\lib\Launcher.js:750:14)
    at ChildProcess.<anonymous> (D:\Users\Daniel\Downloads\destreamer-master\node_modules\puppeteer\lib\Launcher.js:741:65)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```
</details>

**Comment by snobu** [comment]
We may have a typo there, i believe you need double backslash on Windows to escape the escape char, e.g. `C:\\Program Files\\...`. Try it out and report back.

**Comment by mcDandy** [comment]
thank you. Did not thing, that this is some type of source file. So it means \ is used with another character to denote tablutors newlines EOF and other special characters.
