### ISSUE TITLE
InvalidTokenError

### ISSUE THREAD

**Issue by PARTHIBAN3691** [snobu/destreamer#351]
It is saying the token is invalid. I don't have any token. Previously it was working fine.
D:\DESTREAMER 64-BIT BY COMPUTING MENTOR>destreamer -i "URL"
Using ffmpeg version git-2020-05-01-39fb1e9 Copyright (c) 2000-2020 the FFmpeg developers

Error [InvalidTokenError]
at Object. (C:\snapshot\destreamer\node_modules\jwt-decode\lib\index.js:9:31)
at Module._compile (pkg/prelude/bootstrap.js:1320:22)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1165:10)
at Module.load (internal/modules/cjs/loader.js:994:32)
at Function.Module._load (internal/modules/cjs/loader.js:894:14)
at Module.require (internal/modules/cjs/loader.js:1034:19)
at Module.require (pkg/prelude/bootstrap.js:1225:31)
at require (internal/modules/cjs/helpers.js:72:18)
at Object. (C:\snapshot\destreamer\build\src\TokenCache.js:15:38)
at Module._compile (pkg/prelude/bootstrap.js:1320:22) {
message: 'Invalid token specified'
}

Unhandled error!
Timeout or fatal error, please check your downloads directory and try again

**Comment by lukaarma** [comment]
Did you try again/any other video?

**Comment by PARTHIBAN3691** [comment]
It is working now. Thanks!
