### ISSUE TITLE
NaCl helper process running without a sandbox

### ISSUE THREAD

**Issue by mikolaje** [snobu/destreamer#360]
I'm running it on Ubuntu 18 server, but it failed with a Browser issue. Is there any way to solve this? Thank you so much.

OS: Ubuntu 18.04.4 LTS  Server

Launch command used:
./destreamer.sh -u xxx -i xxx --verbose

<details>
<summary>Verbose  log</summary>
  
```

[VERBOSE] Using ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers

Username: xxx

[WARNING] .token_cache not found.

Launching headless Chrome to perform the OpenID Connect dance...

[ERROR] Error: Failed to launch the browser process!
[29352:29352:0401/074847.514650:ERROR:browser_main_loop.cc(1439)] Unable to open X display.
[0401/074847.545333:ERROR:nacl_helper_linux.cc(307)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/opt/destreamer/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.helper_js_1.helper.addEventListener (/opt/destreamer/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
</details>

**Comment by snobu** [comment]
You'll need an X server since we're spawning a browser window. If you don't have X installed you can use a local one and forward graphics over X11 protocol via `ssh -XY your.ubuntu.server`. On Windows you can use Xming (http://www.straightrunning.com/XmingNotes/).

**Comment by mikolaje** [comment]
Aright. Thanks a lot
