### ISSUE TITLE
Error: Failed to launch the browser process! on Windows (WSL and cmd.exe)

### ISSUE THREAD

**Issue by Cathaiste** [snobu/destreamer#361]
Hi. First of all thanks for this tool that surely will by amazing when I will be able to use it ! 
Now I have been searching through the issues and have seen a lot of related issues but no answers to them, I have tried multiple things such as doing once again the whole installation in the Windows' cmd.exe, using Xming, changing the browser path, but it seems it is not working, always getting on the ame error. 

OS: Windows 10 WSL Ubuntu 20.04 LTS

Launch command used: ./destreamer.sh -i "https://web.microsoftstream.com/video/myvideo" -v

<details>
<summary>Verbose  log</summary>
  
```
[VERBOSE] Using ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers


[WARNING] .token_cache not found.

Launching headless Chrome to perform the OpenID Connect dance...

[ERROR] Error: Failed to launch the browser process!
/mnt/c/Users/vicol/Documents/Projets/sanef/destreamer/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/mnt/c/Users/vicol/Documents/Projets/sanef/destreamer/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/mnt/c/Users/vicol/Documents/Projets/sanef/destreamer/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (node:events:390:22)
    at Interface.close (node:readline:514:8)
    at Socket.onend (node:readline:248:10)
    at Socket.emit (node:events:390:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
```
</details>

Can I get a bit of help on this one ? 

Thanks a lot !

**Comment by snobu** [comment]
You're missing libgtk, try sudo apt install libgtk or whatever the package name is for libgtk in apt.

**Comment by snobu** [comment]
Also why are you making your life more difficult with WSL? Just install Node on Windows and build there.

**Comment by Cathaiste** [comment]
Yeah I know, Ok, thanks it fixed it !
