### ISSUE TITLE
HTTP code 400

### ISSUE THREAD

**Issue by thelight0134** [snobu/destreamer#377]
OS: Windows 10

Launch command used: `destreamer.cmd -i https://web.microsoftstream.com/video/d5ff60e9-f269-4397-a0b2-8136de5f85b1 -v`

<details>
<summary>Verbose  log</summary>
  
```
[VERBOSE] Using ffmpeg version 4.3.1-2020-11-08-essentials_build-www.gyan.dev Copyright (c) 2000-2020 the FFmpeg developers

Access token still good for 40 minutes.


[VERBOSE] Session and API info
         API Gateway URL: https://aase-1.api.microsoftstream.com/api/
         API Gateway version: 1.4-private

Parsing video/group urls

[VERBOSE] List of GUIDs and corresponding output directory
        https://web.microsoftstream.com/video/d5ff60e9-f269-4397-a0b2-8136de5f85b1 => videos

Fetching videos info...


Downloading Video: Wednesday's Class


[VERBOSE] Extra video info
         Video m3u8 playlist URL: https://aase-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackurl=https://str
aase1su021.azureedge.net/89458e96-1b29-4e50-84cf-1b17f432c503/v.ism/manifest(format=m3u8-aapl)
         Video tumbnail URL: null
         Video subtitle URL (may not exist): undefined
         Video total chunks: 106.16666666666667

Spawning ffmpeg with access token and HLS URL. This may take a few seconds...



[WARNING] Got HTTP code 400. Retrying request...

[WARNING] Here is the error message:
Buffer(128) [Uint8Array] [
  123,  34, 101, 114, 114, 111, 114,  34,  58, 123,  34,  99,
  111, 100, 101,  34,  58,  34,  73, 110, 118,  97, 108, 105,
  100,  86, 101, 114, 115, 105, 111, 110,  34,  44,  34, 109,
  101, 115, 115,  97, 103, 101,  34,  58,  34,  84, 104, 101,
   32,  65,  80,  73,  32, 118, 101, 114, 115, 105, 111, 110,
   32, 109, 117, 115, 116,  32,  98, 101,  32, 115, 112, 101,
   99, 105, 102, 105, 101, 100,  32, 105, 110,  32, 116, 104,
  101,  32, 117, 114, 108,  32,  97, 115,  32,  97,  32,  39,
   97, 112, 105,  45,
  ... 28 more items
]

[WARNING] We called this URL: https://aase-1.api.microsoftstream.com/api/null

[ERROR] Error: Request failed with status code 400
    at createError (D:\Code\destreamer\node_modules\axios\lib\core\createError.js:16:15)
    at settle (D:\Code\destreamer\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (D:\Code\destreamer\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
</details>

**Comment by snobu** [comment]
Try adding `-x` (Don't render thumbnails) to your command line.
@lukaarma I think we should make that the default since the thumbnail API is becoming highly non-deterministic :)

**Comment by thelight0134** [comment]
Thank you, it works :}
