### ISSUE TITLE
Failed to download some MS Stream videos

### ISSUE THREAD

**Issue by mexbeb** [snobu/destreamer#379]
Destreamer can't download some videos even though from the MS Stream player I can watch them.

OS: MacOs Catalina 10.15.7

Launch command used: ./destreamer.sh -o /Users/******/Desktop/ -u ******  --format mp4 -f links.txt --skip

<details>
<summary>Verbose  log</summary>
  
```
Spawning ffmpeg with access token and HLS URL. This may take a few seconds...



[WARNING] Got HTTP code 400. Retrying request...

[WARNING] Here is the error message: 
Buffer(128) [Uint8Array] [
  123,  34, 101, 114, 114, 111, 114,  34,  58, 123,  34,  99,
  111, 100, 101,  34,  58,  34,  73, 110, 118,  97, 108, 105,
  100,  86, 101, 114, 115, 105, 111, 110,  34,  44,  34, 109,
  101, 115, 115,  97, 103, 101,  34,  58,  34,  84, 104, 101,
   32,  65,  80,  73,  32, 118, 101, 114, 115, 105, 111, 110,
   32, 109, 117, 115, 116,  32,  98, 101,  32, 115, 112, 101,
   99, 105, 102, 105, 101, 100,  32, 105, 110,  32, 116, 104,
  101,  32, 117, 114, 108,  32,  97, 115,  32,  97,  32,  39,
   97, 112, 105,  45,
  ... 28 more items
]

[WARNING] We called this URL: https://euno-1.api.microsoftstream.com/api/null

[ERROR] Error: Request failed with status code 400
    at createError (/Users/******/destreamer/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/******/destreamer/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/******/destreamer/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```
</details>

**Comment by snobu** [comment]
Thank you. I will add a patch for no thumbnail. Had no idea it could return null. Not that I have the API specs or anything.

Cheers!

**Comment by snobu** [comment]
Fixed via https://github.com/snobu/destreamer/commit/7d91f32af297ed745e5342ab98eecb17d062720b.
Thank you for your help, @mexbeb!
