### ISSUE TITLE
Sharepoint.com

### ISSUE THREAD

**Issue by safresh0999** [snobu/destreamer#380]
First of all, thank you for the work you have done.
Is there any hope that the project will be updated, allowing downloads from sharepoint.com? (some professors do not allow download of videos...)

**Comment by carlosmendes-7** [comment]
This subject has been addressed in issue #275

**Comment by palmerj** [comment]
Note that in the last few weeks I've noticed a change where you can't even download the videos from sharepoint. Looks like only the organiser can.

_Q1 of 2021, only the meeting recorder and organizer will be able to download the meeting recording. All other attendees will only be able to view it._

https://support.microsoft.com/en-us/office/play-and-share-a-meeting-recording-in-teams-7d7e5dc5-9ae4-4b94-8589-27496037e8fa#bkmk_downloadmeetingrecording

**Comment by q7z** [comment]
Bumping the last comment by @palmerj

**Comment by GeeWee** [comment]
Can confirm that destreamer no longer works for meeting recordings as they are shared in Sharepoint now.

**Comment by Valeri0p** [comment]
As someone mentioned in #275 someone has developed a new tool, but for now we've been using a workaround to open the video file directly:

- Go to the "files" section of your teams channel;
- Open the "Recordings" folder;
- Right click on the video file and select copy link;
- You should get a direct link to the .mp4 file, you can view it in your browser or download it.

The link structure should be something like `https://[ORGANIZATION].sharepoint.com/sites/[FOLDER NAME, USUALLY THE NAME OF THE TEAM GROUP OR SUBJECT]/Shared%20Documents/General/Recordings/[FILENAME OF THE RECORDING WITH %20 INSTEAD OF SPACES].mp4`

If you only have a link to the sharepoint player you can try to recover the direct link to the mp4 file by using some website like https://www.url-encode-decode.com/ to remove the utf-8 to ascii encoding and then editing the url to look like the example above.

Scusate per la grammatica ma l'ho scritto un po di fretta 😅

**Comment by snobu** [comment]
Looks like this shouldn't take too much effort to implement into destreamer. Will take a look. Thanks for your writeup, appreciate the effort.

**Comment by Valeri0p** [comment]
You are welcome 😊 ("writeup", è giusto la descrizione di un url 😅)
Just so you know,  "General" was the name of the channel, and the folder "Recordings" might not have the same name for everyone.

Honestly I don't know how universal this method is, maybe it only works in my organization because of some oversight when setting up the privileges.
I haven't looked at his code, but I assume @kylon 's software might be more robust and harder to patch for Microsoft seeing the presence of FFmpeg to obtain the video stream (I guess).

**Comment by wad11656** [comment]
> As mentioned in #275 someone has developed a new tool, but in the meantime we've been using a workaround to open the video files directly:
> 
> * Go to the "Files" section of your teams channel;
> * Open the "Recordings" folder;
> * Right click on the video file and select copy link;
> * You should get a direct link to the .mp4 file, you can view it in your browser or download it, no restrictions.
> 
> The link structure should be something like this: `https://[ORGANIZATION].sharepoint.com/sites/[FOLDER NAME, USUALLY THE NAME OF THE TEAM GROUP OR SUBJECT]/Shared%20Documents/General/Recordings/[FILENAME OF THE RECORDING WITH %20 INSTEAD OF SPACES (or other ascii to utf-8 codes)].mp4`
> 
> If you only have a link to the sharepoint player you can try to recover the direct link to the mp4 file by using some website like https://www.url-encode-decode.com/ to remove the utf-8 to ascii encoding and then editing the url to look like the example above. (no need to convert it back when opening the new url btw).
> 
> Scusate per la grammatica ma l'ho scritto un po di fretta 😅

After a bunch of fenagling I finally got a url that ends in `.mp4` (`https://companyName-my.sharepoint.com/:v:/r/personal/employeeName_companyName_com/Documents/Recordings/Company%20Meeting-20210712-Meeting%20Recording.mp4`) but I get a "Sorry, you don't have access." :

![image](https://user-images.githubusercontent.com/16929664/125511646-f00c8063-8de7-475d-8ec1-9874015c323f.png)

**Comment by Valeri0p** [comment]
Yeah I saw links with the ":v:" sometimes in the link generated inside the chat, they don't contain the full path.
Again it probably depends on how the organization has set up its privileges.

When I get my url from Sharepoint or the Files section on Teams I get this: (after going trough https://www.url-encode-decode.com/)
`https://[ORG].sharepoint.com/sites/[TEAM NAME]/Shared Documents/Forms/AllItems.aspx?id=/sites/[TEAM NAME]/Shared Documents/General/Recordings/[FILENAME].mp4&parent=/sites/[TEAM NAME]/Shared Documents/General/Recordings`

That can be edited into this:
`https://[ORG].sharepoint.com/sites/[TEAM NAME]/Shared Documents/General/Recordings/[FILENAME].mp4`

[ORG] is already present int the url, [TEAM NAME] should be easy to recover, "General/Recordings/" might change as I said up there and [FILENAME] if not apparent int the url is obtainable by opening the details section of the Sharepoint player; 
It's mostly custom but it look something like:
`[Custom part by the organizer] [dd.mm.aa date]-[aaaammdd, basically ISO 8601-like date]_[hhmmss time]-Meeting Recording.mp4`

...also by looking at that "other details" section there's a button that says "copy direct link" (it's in italian so idk the exact name 😅)

**Comment by MaschineBrennt** [comment]
It doesn't work with sharepoint

**Comment by darderik** [comment]
The issue related to invalid urls seems to be located in this [regex check](https://github.com/snobu/destreamer/blob/de158e3119d49276b39871a657414ea5ce830c34/src/Downloaders.ts#L188)


![Screenshot (18)_LI](https://user-images.githubusercontent.com/14088415/138250088-6bfaf040-60ca-4c5a-aed0-6e29de2acc91.jpg)

I don't know if I got the regex right, but this is what I wrote in order to match correctly the url

`(?<domain>https:\/\/.+\.sharepoint\.com)(?<basesite>\/:.?:+\/*\/.*)(?:(?<filename>\/.*\.mp4)|\/.*id=(?<paramFilename>.*mp4))`
![Screenshot (19)_LI](https://user-images.githubusercontent.com/14088415/138250457-57d23eef-e352-4049-81e1-1f63da473863.jpg)

Unfortunately, this resulted in another error i'm not able to fix,as i'm unable to debug typescript

![Screenshot (20)](https://user-images.githubusercontent.com/14088415/138250817-9de5ae37-0635-4bfa-91a1-235c166d6782.png)


I sincerely hope these info will help you :)

**Comment by gionac** [comment]
Hello everybody, 
I'm using destreamer to download some videos from sharedpoint.
The wird thing is i can downlaod without problmes videos that were recorded until last week, but with the recordings of this week I'm receiving this error:

`[ERROR] Error: Request failed with status code 404
    at createError (C:\devepolpents\destreamer\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\devepolpents\destreamer\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\devepolpents\destreamer\node_modules\axios\lib\adapters\http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)



[FATAL ERROR] Unhandled error!
Timeout or fatal error, please check your downloads directory and try again`

It seems that with the videos of this week destreamer is unable to find the .mp4 file in the page code...
Does anyone have any diea of why?

Thank you for your work!

**Comment by lukaarma** [comment]
> @lukaarma can you check one thing please. With your new branch, when you get the API URL formed, dump the JSON output for the streams,

@snobu I could not find something like that but I'll e-mail you a couple of json I got so that you could take a look. When I have more time I'll dig more into the api to see if I missed something.
<br><br>

> it seems to be a timeout problem because Chrome close it when i'm writing password or second authentication factor.

@DaniDiaz71 Could you please make sure that you are on the latest version of the Sharepoint branch? There was an error during the login process that should have been fixed, if you are on the latest branch and you are still having trouble loggin in please open a separate issue.
<br><br>

> But in our company, now the url of the online video for meeting recording changed to something like below: https://xxxxxx-my.sharepoint.com/%3Av%3A/g/personal/xxxxxx_xxxxxx_xxxxxx_com/EQ5y7SkmWbRDtzS0uE3Rd2sBjxHSkc_GkbzTx9PreCrXig

@snqqyj if you are comfortable enough to share the complete url with me via the e-mail you find on my profile it would be great and really help me. If you don't want could you at least tell me if it ends with '.mp4'
<br><br>

> The wird thing is i can downlaod without problmes videos that were recorded until last week, but with the recordings of this week I'm receiving this error:

@gionac Was there any change in the url of the video between last week and this one? Could you please check.
<br><br>

**Comment by tipicoenlauniFB** [comment]
I have the same problem. I can't download videos from this week.

**Comment by gionac** [comment]
> @gionac Was there any change in the url of the video between last week and this one? Could you please check.

@lukaarma I copy there the two links. The first (newer) doesn't work, instead the second works like charm..

[...]/L1%20-%20relativit%C3%A0%20e%20Locard%20-%20L2%20-%2020211026_152611-Meeting%20Recording.mp4?csf=1&web=1&e=XxMFGP

[...]/L0-lab-20211005_160042-Meeting%20Recording.mp4?csf=1&web=1&e=7E0Pk7

I omitted the first because it's identical

**Comment by lukaarma** [comment]
> I omitted the first because it's identical

@gionac could you please open a new issue and provide me the full verbose output of your command (add `-- verbose` to your command)
I don't see anything special in your link so it may be something else

**Comment by gionac** [comment]
> > I omitted the first because it's identical
> 
> @gionac could you please open a new issue and provide me the full verbose output of your command (add `-- verbose` to your command) I don't see anything special in your link so it may be something else

I did a new issue here, with the verbose output, here: https://github.com/snobu/destreamer/issues/416

Thank you @lukaarma !

**Comment by martingercke** [comment]
> I also had an issue with personal videos.
I needed to add "personal" to the list:
const shareUrlRegex = new RegExp(/(?<domain>https:\/\/.+\.sharepoint\.com).*?(?<baseSite>\/(?:teams|sites|personal)\/.*?)(?:(?<filename>\/.*\.mp4)|\/.*id=(?<paramFilename>.*mp4))/);

**Comment by muzso** [comment]
> I also had an issue with personal videos.
> I needed to add "personal" to the list:
> const shareUrlRegex = new RegExp(/(?https://.+.sharepoint.com)._?(?/(?:teams|sites|personal)/._?)(?:(?/.*.mp4)|/.*id=(?.*mp4))/);

Same here. After adding "|personal" to the regex, download started to work (even for videos where I have no download permission). Thanks!

**Comment by WilliamWsyHK** [comment]
Thanks for @muzso advise, and I have created a PR base on this, as well to include a small fix on the file name with characters that requires `encodeURIComponent`-ed.
