### ISSUE TITLE
Error: Could not find MIME for Buffer

### ISSUE THREAD

**Issue by KarlOmatic** [snobu/destreamer#391]
I could download every Video I wanted except one. I keep getting this Error:

[ERROR] Error: Could not find MIME for Buffer <null>
    at Jimp.parseBitmap (C:\snapshot\destreamer-aria2c_forRealNow\node_modules\@jimp\core\dist\utils\image-bitmap.js:187:15)
    at Jimp.parseBitmap (C:\snapshot\destreamer-aria2c_forRealNow\node_modules\@jimp\core\dist\index.js:431:32)
    at new Jimp (C:\snapshot\destreamer-aria2c_forRealNow\node_modules\@jimp\core\dist\index.js:384:13)
    at _construct (C:\snapshot\destreamer-aria2c_forRealNow\node_modules\@babel\runtime\helpers\construct.js:19:21)
    at C:\snapshot\destreamer-aria2c_forRealNow\node_modules\@jimp\core\dist\index.js:926:32
    at new Promise (<anonymous>)
    at Function.<anonymous> (C:\snapshot\destreamer-aria2c_forRealNow\node_modules\@jimp\core\dist\index.js:925:10)
    at render (C:\snapshot\destreamer-aria2c_forRealNow\node_modules\terminal-image\index.js:74:27)
    at fallback (C:\snapshot\destreamer-aria2c_forRealNow\node_modules\terminal-image\index.js:104:19)
    at C:\snapshot\destreamer-aria2c_forRealNow\node_modules\term-img\index.js:25:10

It really has worked with every video before and after my attempts, but just not with this one

**Comment by snobu** [comment]
Try adding -x to your command line. It will skip thumbnail rendering which is failing for that video.

**Comment by KarlOmatic** [comment]
Thanks. that solved my issue
