### ISSUE TITLE
Issue error 400 not succeful download

### ISSUE THREAD

**Issue by joaopaul023** [snobu/destreamer#394]
I downloaded several videos of my classes from the same group, but when I reach a specific link this error 400 appears and I can't download the video.

Fresh access token dropped into .token_cachen

Parsing video/group urls
Downloading video info, this might take a while...
Trying to launch and connect to aria2c...

Connected to aria2 daemon!

Downloading video no.1

[WARNING] Got HTTP code 400. Retrying request...

[ERROR] Error: Request failed with status code 400
    at createError (C:\snapshot\destreamer-aria2c_forRealNow\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\snapshot\destreamer-aria2c_forRealNow\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\snapshot\destreamer-aria2c_forRealNow\node_modules\axios\lib\adapters\http.js:244:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1224:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

[FATAL ERROR] Unhandled error or uncaught exception!
Please check your download directory/directories and try again.
If this keep happening please report it on github "https://github.com/snobu/destreamer/issues"

**Comment by snobu** [comment]
The Aria branch you seem to be using is unstable, i would try adding -x to your command line to skip a few experimental features, other than that, if it still doesn't work, clone and compile the master branch instead.

**Comment by joaopaul023** [comment]
Woww It worked perfectly, thank you very much!
