### ISSUE TITLE
HTTP Code 404 for valid URL

### ISSUE THREAD

**Issue by popjin9** [snobu/destreamer#400]
OS: Windows 10

Launch command used: destreamer.cmd -v -i "https://web.microsoftstream.com/video/ce9f5d4a-3bde-4931-9d8c-1a90df526909"

Issue: The program returns a 404 error when downloading lecture recordings. I've tried with other links from my university and added with -x flag with no difference.

<details>
<summary>Verbose  log</summary>
  
[VERBOSE] Using ffmpeg version 2021-08-25-git-e41bd075dd-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers

Access token still good for 41 minutes.

[VERBOSE] Session and API info
         API Gateway URL: https://aase-1.api.microsoftstream.com/api/
         API Gateway version: 1.4-private

Parsing video/group urls

[VERBOSE] List of GUIDs and corresponding output directory
        https://web.microsoftstream.com/video/ce9f5d4a-3bde-4931-9d8c-1a90df526909 => videos

Fetching videos info...

[WARNING] Got HTTP code 404. Retrying request...

[WARNING] Here is the error message:
{
  error: { code: 'NotFound', message: 'The video could not be found' }
}

[WARNING] We called this URL: https://aase-1.api.microsoftstream.com/api/videos/ce9f5d4a-3bde-4931-9d8c-1a90df526909?$expand=creator&api-version=1.4-private

[ERROR] Error: Request failed with status code 404
    at createError (C:\Users\[Redacted]\Desktop\destreamer\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\[Redacted]\Desktop\destreamer\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\[Redacted]\Desktop\destreamer\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
</details>

**Comment by snobu** [comment]
Are you able to watch that video with your browser, logged in as the same user as the one you use to login to destreamer?

**Comment by popjin9** [comment]
Yes - opening the link with my browser takes me directly to the video page

**Comment by lukaarma** [comment]
I'm sorry for the late reply but life got in the way. Do you still have this issue?
