### ISSUE TITLE
[ERROR] Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by Halo1211** [snobu/destreamer#410]
[ERROR] Error: Failed to launch the browser process!
/mnt/c/Users/Albert BS/destreamer/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/mnt/c/Users/Albert BS/destreamer/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)    at Interface.helper_js_1.helper.addEventListener (/mnt/c/Users/Albert BS/destreamer/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:203:15)
    at Interface.close (readline.js:397:8)
    at Socket.onend (readline.js:173:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

any fix please

**Comment by Halo1211** [comment]
still got the error 
![image](https://user-images.githubusercontent.com/42713232/136668547-e4f07536-4d74-4d77-9f9d-63cfc8cf3cbd.png)

**Comment by Halo1211** [comment]
> You're probably missing a few dependencies for Chromium. Either plugin your own browser - which is what i strongly suggest (see README for instructions) - or try to run this:
> 
> ```
> sudo apt install libcups2 libnss3-dev librust-atk-sys-dev libatk-bridge2.0-dev librust-gtk-sys-dev -yy
> ```
![image](https://user-images.githubusercontent.com/42713232/136669030-c0c41160-dfb0-412b-bc5b-5e253b6937be.png)
![image](https://user-images.githubusercontent.com/42713232/136669043-452d405d-8fdf-42d7-abe8-19a6c16cc31f.png)

**Comment by Halo1211** [comment]
![image](https://user-images.githubusercontent.com/42713232/136669576-04d0fde2-857e-40c6-a85d-58b3e70ed431.png)

**Comment by lukaarma** [comment]
Closing, if you need more help reply below and reopen the issue
