### ISSUE TITLE
Error 404 with sharepoint registrations done after 19/10/2021

### ISSUE THREAD

**Issue by gionac** [snobu/destreamer#416]
Hello everybody,
I'm using destreamer to download some videos from sharedpoint.
The wird thing is i can download without problemes videos that were recorded until last week, but with the recordings of this week I'm receiving this error:

OS: Windows 11

Launch command used: .\destreamer.cmd -f list.txt --verbose
the file list.txt contains the following links:

"[...]/L1%20-%20relativit%C3%A0%20e%20Locard%20-%20L2%20-%2020211026_152611-Meeting%20Recording.mp4?csf=1&web=1&e=XxMFGP

[...]/L0-lab-20211005_160042-Meeting%20Recording.mp4?csf=1&web=1&e=7E0Pk7"

the first part is identical, so i omitted it

<details>
<summary>Verbose  log</summary>
  
```
C:\devepolpents\destreamer>.\destreamer.cmd -f list.txt --verbose

[VERBOSE] Using ffmpeg version 2021-10-03-git-2761a7403b-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers


[VERBOSE] Using aria2 version 1.36.0

Parsing input file

[VERBOSE] List of urls and corresponding output directory
        https://[myOrganizazion]/Documenti%20condivisi/General/Recordings/Solo%20visualizzazione/L1%20-%20relativit%C3%A0%20e%20Locard%20-%20L2%20-%2020211026_152611-Meeting%20Recording.mp4?csf=1&web=1&e=XxMFGP => videos

Downloading SharePoint videos...


Launching headless Chrome to perform the OpenID Connect dance...
Navigating to login page...
Waiting for target!
We are logged in.
At this point Chromium's job is done, shutting it down...


[VERBOSE] Stream login browser closing...

[VERBOSE] Stream login browser closed

[VERBOSE] Requesting video info for '/sites/CittadinanzaDigitaleeTecnocivismo/_api/web/GetListUsingPath(DecodedUrl=@a1)/RenderListDataAsStream?@a1='/sites/CittadinanzaDigitaleeTecnocivismo/Documenti condivisi/General/Recordings/Solo visualizzazione/L1 - relatività e Locard - L2 - 20211026_152611-Meeting Recording.mp4''

[ERROR] Error: Request failed with status code 404
    at createError (C:\devepolpents\destreamer\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\devepolpents\destreamer\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\devepolpents\destreamer\node_modules\axios\lib\adapters\http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)



[FATAL ERROR] Unhandled error!
Timeout or fatal error, please check your downloads directory and try again
```
</details>

Does anyone have any diea of why?

Thank you for your work!

**Comment by tipicoenlauniFB** [comment]
I use Sharedown to download Sharepoint's videos. It works with the new videos.
https://github.com/kylon/Sharedown

Maybe the developer from Sharepoint's branch could fuse Sharedown with Destreamer.

**Comment by gionac** [comment]
> I use Sharedown to download Sharepoint's videos. It works with the new videos. https://github.com/kylon/Sharedown
> 
> Maybe the developer from Sharepoint's branch could fuse Sharedown with Destreamer.

Yess you are right, it works, thank you!

**Comment by FraH90** [comment]
Hi guys, I'd like to know if this bug is still present.

If so, there's any chance it would get fixed? I'm planning to using destreamer for downloading my university videolesson.

Sharedown is not really at the level of destreamer, you can only download one video at a time... I'd really love if destreamer could be used with sharepoint.
