### ISSUE TITLE
Chromium not working on Mac M1

### ISSUE THREAD

**Issue by tamlhp** [snobu/destreamer#458]
+ I used the branch https://github.com/snobu/destreamer/tree/aria2c_forRealNow
+ I installed chromium (brew install chromium --no-quarantine) on Mac M1
+ I even tried to edit the src/destreamer.ts:
executablePath: '/opt/homebrew/bin/chromium',
or
executablePath: "'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' --profile-directory=Default", 
+ and rebuild (npm run build)

but it always use /usr/bin/chromium-browser:
[ERROR] Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT

OS:

Launch command used:
./destreamer.sh -i "https://web.microsoftstream.com/video/cad98f79-b53e-4201-9870-c1a6fceca1fa" --verbose

<details>
<summary>Verbose  log</summary>
  
```
[VERBOSE] Using ffmpeg version 5.1.1 Copyright (c) 2000-2022 the FFmpeg developers


[VERBOSE] Using aria2 version 1.36.0


[WARNING] .token_cache not found.

Launching headless Chrome to perform the OpenID Connect dance...

[ERROR] Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/Users/s2993348/workspace/github/destreamer/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at ChildProcess.<anonymous> (/Users/s2993348/workspace/github/destreamer/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)



[FATAL ERROR] Unhandled error or uncaught exception!
```
</details>

**Comment by tamlhp** [comment]
It is the problem of puppeteer. 
Solution: https://github.com/puppeteer/puppeteer/issues/6634
