### ISSUE TITLE
Support for New Stream (on SharePoint)

### ISSUE THREAD

**Issue by arathburgos05** [snobu/destreamer#493]
There is a new version for MS Stream (on SharePoint): https://learn.microsoft.com/en-us/stream/streamnew/new-stream

Unfortunately, destreamer seems to be working with new version. Also I cannot use Stream (Classic) because it's locked by organization:
![image](https://github.com/snobu/destreamer/assets/25379464/e2351ef5-084e-42cf-a933-a5b7f6213b92)

I'm using destreamer v2.1.0.

OS:
Windows 10 x64

Launch command used:
$ destreamer-v3.exe -i "https://[ORG]-my.sharepoint.com/✌️/g/personal/[ACCOUNT]_[ORG]_com/[HASH]?nav=eyJyZWxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

```
Access token still good for 39 minutes.

Parsing video/group urls

[WARNING] Invalid url '[URL]', skipping..
Downloading video info, this might take a while...
Trying to launch and connect to aria2c...

Connected to aria2 daemon!
Exiting, this will take some seconds...

[ERROR] Error
    at DownloadManager.close (C:\snapshot\destreamer-aria2c_forRealNow\build\src\DownloadManager.js:109:23)
    at async downloadVideo (C:\snapshot\destreamer-aria2c_forRealNow\build\src\destreamer.js:265:5)
    at async main (C:\snapshot\destreamer-aria2c_forRealNow\build\src\destreamer.js:300:5)



[FATAL ERROR] Unhandled error or uncaught exception!
Please check your download directory/directories and try again.
If this keep happening please report it on github "https://github.com/snobu/destreamer/issues"
```
</details>

Is the any workaround or plans to support New Stream?

Nice work. Thanks :)

**Comment by hostar** [comment]
try this for now https://github.com/snobu/destreamer/issues/487#issuecomment-1605586156

**Comment by maxwell-bland** [comment]
A notes as well from trying out destreamer yesterday, not sure if it was worth opening a second issue.

On private sharepoint servers, the url will not be recognized when parsing sys.argv. The VideoManifest url from the browser traffic could be grabbed and fed to `ffmpeg -i <url>` to grab the video in this case.
