### ISSUE TITLE
A few problems

### ISSUE THREAD

**Issue by snobu** [snobu/destreamer#53]
`tokencache` branch

* Login is broken (at least for me via 2FA).

```
Launching headless Chrome to perform the OpenID Connect dance...
Navigating to login page...
We are logged in.
Unhandled error!
Timeout or fatal error, please check your downloads and try again if necessary.

Error: Evaluation failed: ReferenceError: sessionInfo is not defined
    at __puppeteer_evaluation_script__:3:26
    at ExecutionContext._evaluateInternal (C:\destreamer\node_modules\puppeteer\lib\ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (C:\destreamer\node_modules\puppeteer\lib\ExecutionContext.js:48:12)    
    at async DoInteractiveLogin (C:\destreamer\destreamer.js:108:19)
    at async main (C:\destreamer\destreamer.js:187:19)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\destreamer\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.evaluate (C:\destreamer\node_modules\puppeteer\lib\DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DoInteractiveLogin (C:\destreamer\destreamer.js:108:19)
    at async main (C:\destreamer\destreamer.js:187:19)
  -- ASYNC --
    at Frame.<anonymous> (C:\destreamer\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.evaluate (C:\destreamer\node_modules\puppeteer\lib\Page.js:860:43)
    at Page.<anonymous> (C:\destreamer\node_modules\puppeteer\lib\helper.js:112:23)
    at DoInteractiveLogin (C:\destreamer\destreamer.js:108:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (C:\destreamer\destreamer.js:187:19)
C:\destreamer\destreamer.js:175
    throw new Error('Killing process..\n');
    ^

Error: Killing process..

    at process.<anonymous> (C:\destreamer\destreamer.js:175:11)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

* this https://github.com/snobu/destreamer/blob/tokencache/destreamer.ts#L208 doesn't work on Windows, we need to construct a OS-specific path with the right delimiter

**Comment by kylon** [comment]
ffmpeg-bar should be removed regardless, it causes more harm than good, i m working with fluent (#39)

**Comment by lukaarma** [comment]
@snobu the error happenes when puppeteer tried to evaluate our values....so it might be 2 things: before the actual video page loads there is another that has the videoId in the URL OR the page does not load the js in time (unlikely)

**Comment by snobu** [comment]
If i add a sleep for 2 seconds right after the session evaluates correctly, so we're in a race condition.

**Comment by lukaarma** [comment]
> My question still stands, can we await on a cookie rather than URL?
> 
> Else we could loop over awaiting page.cookies() and keep evaluating until we succeed. Still a little too nondeterministic to be safe but probably better than trying to await a DOM element.

We could do it like this seeing as if we wait that the cookie "Authorization" we are sure that authToken is set but if we have to do it like this we can do it on evaluate itself and quit if it's not set.
Like this:
```   
    let session = null;
    let tries: number = 0;

    while (!session) {
        try {
            let sessionInfo: any;
            let session = await page.evaluate(
                () => {
                    return {
                        AccessToken: sessionInfo.AccessToken,
                        ApiGatewayUri: sessionInfo.ApiGatewayUri,
                        ApiGatewayVersion: sessionInfo.ApiGatewayVersion
                    };
                }
            );
        } catch (error) {
            if (tries < 5){
                session = null;
                tries++;
                await sleep(3000);
            } else {
                throw(error);
            }
        }
    }
```

**Comment by snobu** [comment]
Yup i think this may be good enough. Can you push it? Will test with my 2FA login.

**Comment by snobu** [comment]
Closing as fixed.
![image](https://user-images.githubusercontent.com/6472374/79049724-01472100-7c2e-11ea-96e8-d2a06c5c6be1.png)
