### ISSUE TITLE
[linux] Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by oscarandrea** [snobu/destreamer#65]
hi, I use arch linux, I installed chromium (which I have always used for destreamer on other linux systems), but when I try to start the process I have this error.

```
Using youtube-dl version 2020.03.24
Using ffmpeg version n4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
Launching headless Chrome to perform the OpenID Connect dance...
(node:610) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn /home/oscar/destreamer/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome EACCES


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/home/oscar/destreamer/node_modules/puppeteer/lib/Launcher.js:750:14)
    at ChildProcess.<anonymous> (/home/oscar/destreamer/node_modules/puppeteer/lib/Launcher.js:741:65)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:610) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:610) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
Thank you

**Comment by kylon** [comment]
Hi,

you don't need to install chromium, puppeteer has its own chromium.

you don't have permissions to run that executable.
chown the node_modules folder to grant permissions for your user
if you use root, don't install node modules with root

**Comment by oscarandrea** [comment]
thanks, in fact destreamer comes from a backup and perhaps had different permissions, I tried to change the owner recursively but it still didn't work, so I trivially cloned the repository again and installed the modules as a normal user, everything works. I thought it was another kind of problem, thanks
