### ISSUE TITLE
Keep getting an error when downloading a video.

### ISSUE THREAD

**Issue by joao44289** [snobu/destreamer#81]
``` 
RangeError: Invalid array length
    at Object.parse (C:\destreamer\node_modules\cli-progress\lib\options.js:48:38)
    at new SingleBar (C:\destreamer\node_modules\cli-progress\lib\single-bar.js:8:24)
    at downloadVideo (C:\destreamer\build\src\destreamer.js:121:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Unhandled error!
Timeout or fatal error, please check your downloads directory and try again
```

I keep this error when trying to download a video. I have tried to download it to a custom path but it's also not working.

**Comment by kylon** [comment]
make sure you are using latest master

[destreamer.js.zip](https://github.com/snobu/destreamer/files/4509738/destreamer.js.zip)

replace, rebuild and run, paste here the log

**Comment by joao44289** [comment]
![Capture](https://user-images.githubusercontent.com/64077887/79862261-c1223400-83cd-11ea-8724-6997048d542f.PNG)
I can't open that file but I think I'm using the latest master. I've set up everything up 10 minutes before I posted this issue.

**Comment by kylon** [comment]
i don't what file is that, the attached one is a zip, use 7zip or something and extract destreamer.js
replace in src in destreamer folder

**Comment by snobu** [comment]
@joao44289 What's your Node version? `node --version`

I can't reproduce this problem on any of the following -
*  13.13.0
 * 12.2.0
 * 10.20.1
 * 8.17.0

**Comment by snobu** [comment]
I also wonder if this is related to the HLS stream, what if the total length returns zero? Could we maybe add some console.logs to dump all the arguments that get passed into cli-progress and ask @joao44289 to give it another go?

**Comment by joao44289** [comment]
> i don't what file is that, the attached one is a zip, use 7zip or something and extract destreamer.js
> replace in src in destreamer folder

Tried that, didn't work still same error.

@snobu The version is 12.16.2

**Comment by snobu** [comment]
Ok, we can rule out the Node version. Can you try it with a different video? Still no go?

**Comment by joao44289** [comment]
> Ok, we can rule out the Node version. Can you try it with a different video URL? Still no go?

Still the same. Tried two other videos from separate people just to be sure and still nothing. I don't know if this is useful information, but I am logging  in my university account to download lectures my professors have uploaded there.

**Comment by kylon** [comment]
ok, lets try something easier
add these lines yourself to destreamer.js

at line 148 add:
```
console.log(process.stdout.columns);
console.log(Math.floor(process.stdout.columns / 3));
console.log(i+" "+j+" "+l);
console.log(video.totalChunks)
```

**Comment by joao44289** [comment]
@kylon still the same error but I have very little coding experience so just to make sure I added those lines correctly:
```javascript
if (argv.verbose)
        console.log(outputDirectories);
		console.log(process.stdout.columns);
		console.log(Math.floor(process.stdout.columns / 3));
		console.log(i+" "+j+" "+l);
		console.log(video.totalChunks)
```

This is how the entire if statement is after adding the lines. Just to make sure I added them correctly.

**Comment by kylon** [comment]
add them before `if (verbose)`

this will not solve the error, i need more logs
add the lines, rebuild and run and paste the logs

**Comment by joao44289** [comment]
How do I rebuild? After I make the changed all I did was open the program through the console, do I need to do anything else?

**Comment by kylon** [comment]
npm run -s build

**Comment by joao44289** [comment]
```RangeError: Invalid array length
    at Object.parse (C:\destreamer\node_modules\cli-progress\lib\options.js:48:38)
    at new SingleBar (C:\destreamer\node_modules\cli-progress\lib\single-bar.js:8:24)
    at downloadVideo (C:\destreamer\build\src\destreamer.js:121:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


Unhandled error!
Timeout or fatal error, please check your downloads directory and try again
```

**Comment by kylon** [comment]
i need all the messages

**Comment by joao44289** [comment]
```
Joao_@DESKTOP-GTRV89 MINGW64 /c/destreamer (master)
$ npm run -s build
Transpiling TypeScript to JavaScript...
TSFILE: C:/destreamer/build/src/Errors.js
TSFILE: C:/destreamer/build/src/CommandLineParser.js
TSFILE: C:/destreamer/build/src/Events.js
TSFILE: C:/destreamer/build/src/Types.js
TSFILE: C:/destreamer/build/src/Metadata.js
TSFILE: C:/destreamer/build/src/PuppeteerHelper.js
TSFILE: C:/destreamer/build/src/Thumbnail.js
TSFILE: C:/destreamer/build/src/TokenCache.js
TSFILE: C:/destreamer/build/src/Utils.js
TSFILE: C:/destreamer/build/test/test.js

Joao_@DESKTOP-GTRV89 MINGW64 /c/destreamer (master)
$ ./destreamer.sh
Options:
  --help                   Show help                                   [boolean]
  --version                Show version number                         [boolean]
  --videoUrls, -i          List of video urls                            [array]
  --videoUrlsFile, -f      Path to txt file containing the urls         [string]
  --username, -u                                                        [string]
  --outputDirectory, -o    The directory where destreamer will save your
                           downloads [default: videos]                  [string]
  --outputDirectories, -O  Path to a txt file containing one output directory
                           per video                                    [string]
  --noExperiments, -x      Do not attempt to render video thumbnails in the
                           console                    [boolean] [default: false]
  --simulate, -s           Disable video download and print metadata information
                           to the console             [boolean] [default: false]
  --verbose, -v            Print additional information to the console (use this
                           before opening an issue on GitHub)
                                                      [boolean] [default: false]



Joao_@DESKTOP-GTRV89I MINGW64 /c/destreamer (master)
$ ./destreamer.sh -i "https://web.microsoftstream.com/video/bb692e32-ef4e-44d1-a4ce-4cbeaf400bee?channelId=6ae8dfa1-03a4-4464-be0f-26d62498a61e"
Using ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers


Access token still good for 24 minutes.

Fetching metadata...
RangeError: Invalid array length
    at Object.parse (C:\destreamer\node_modules\cli-progress\lib\options.js:48:38)
    at new SingleBar (C:\destreamer\node_modules\cli-progress\lib\single-bar.js:8:24)
    at downloadVideo (C:\destreamer\build\src\destreamer.js:121:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


Unhandled error!
Timeout or fatal error, please check your downloads directory and try again


Joao_@DESKTOP-GTRV89 MINGW64 /c/destreamer (master)
$ ^C

Joao_@DESKTOP-GTRV89 MINGW64 /c/destreamer (master)
$
```

**Comment by kylon** [comment]
move the new lines to line 152, before pbar
rebuild and run

you can just paste the logs when you run destreamer

**Comment by joao44289** [comment]
```

Joao_@DESKTOP-GTRV34I MINGW64 /c/destreamer (master)
$ npm run -s build
Transpiling TypeScript to JavaScript...
TSFILE: C:/destreamer/build/src/Errors.js
TSFILE: C:/destreamer/build/src/CommandLineParser.js
TSFILE: C:/destreamer/build/src/Events.js
TSFILE: C:/destreamer/build/src/Types.js
TSFILE: C:/destreamer/build/src/Metadata.js
TSFILE: C:/destreamer/build/src/PuppeteerHelper.js
TSFILE: C:/destreamer/build/src/Thumbnail.js
TSFILE: C:/destreamer/build/src/TokenCache.js
TSFILE: C:/destreamer/build/src/Utils.js
TSFILE: C:/destreamer/build/test/test.js

Joao_@DESKTOP-GTRV34I MINGW64 /c/destreamer (master)
$ ./destreamer.sh
Options:
  --help                   Show help                                   [boolean]
  --version                Show version number                         [boolean]
  --videoUrls, -i          List of video urls                            [array]
  --videoUrlsFile, -f      Path to txt file containing the urls         [string]
  --username, -u                                                        [string]
  --outputDirectory, -o    The directory where destreamer will save your
                           downloads [default: videos]                  [string]
  --outputDirectories, -O  Path to a txt file containing one output directory
                           per video                                    [string]
  --noExperiments, -x      Do not attempt to render video thumbnails in the
                           console                    [boolean] [default: false]
  --simulate, -s           Disable video download and print metadata information
                           to the console             [boolean] [default: false]
  --verbose, -v            Print additional information to the console (use this
                           before opening an issue on GitHub)
                                                      [boolean] [default: false]



Joao_@DESKTOP-GTRV34I MINGW64 /c/destreamer (master)
$ ./destreamer.sh -i "https://web.microsoftstream.com/video/bb692e32-ef4e-44d1-a4ce-4cbeaf400bee?channelId=6ae8dfa1-03a4-4464-be0f-26d62498a61e"
Using ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers


Access token still good for 4 minutes.

Fetching metadata...
RangeError: Invalid array length
    at Object.parse (C:\destreamer\node_modules\cli-progress\lib\options.js:48:38)
    at new SingleBar (C:\destreamer\node_modules\cli-progress\lib\single-bar.js:8:24)
    at downloadVideo (C:\destreamer\build\src\destreamer.js:121:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


Unhandled error!
Timeout or fatal error, please check your downloads directory and try again
```
and to make sure I did it correctly
```
const outDirsIdxInc = outputDirectories.length > 1 ? 1:0;
    for (let i=0, j=0, l=metadata.length; i<l; ++i, j+=outDirsIdxInc) {
		console.log(process.stdout.columns);
		console.log(Math.floor(process.stdout.columns / 3));
		console.log(i+" "+j+" "+l);
		console.log(video.totalChunks)
        const video = metadata[i];
```

**Comment by kylon** [comment]
yes, but i see no logs, maybe this is an unrelated error due to something else...


Metadata.ts
con you please add:
`console.log('1')` line 50
`console.log('2')` line 52
`console.log('3')` line 54

again rebuild and paste logs

**Comment by joao44289** [comment]
The download command or the rebuild command?

**Comment by kylon** [comment]
when you run destreamer, add -v option

**Comment by joao44289** [comment]
```
$ ./destreamer.sh -v -i "https://web.microsoftstream.com/video/fc7f80ea-e380-44db-8e2a-f34b64389a08?list=user&userId=82be014f-7d7f-4f3e-9079-d13113f1ade6"
Using ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers

Video URLs:
[
  'https://web.microsoftstream.com/video/fc7f80ea-e380-44db-8e2a-f34b64389a08?list=user&userId=82be014f-7d7f-4f3e-9079-d13113f1ade6'
]

Access token has expired.
Launching headless Chrome to perform the OpenID Connect dance...
Navigating to login page...
We are logged in.
Wrote access token to token cache.
At this point Chromium's job is done, shutting it down...

Fresh access token dropped into .token_cache
Video GUIDs:
[ 'fc7f80ea-e380-44db-8e2a-f34b64389a08' ]
Fetching metadata...
Calling https://euno-1.api.microsoftstream.com/api/videos/fc7f80ea-e380-44db-8e2a-f34b64389a08?api-version=1.4-private
1
2
3
[ 'videos' ]
RangeError: Invalid array length
    at Object.parse (C:\destreamer\node_modules\cli-progress\lib\options.js:48:38)
    at new SingleBar (C:\destreamer\node_modules\cli-progress\lib\single-bar.js:8:24)
    at downloadVideo (C:\destreamer\build\src\destreamer.js:121:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


Unhandled error!
Timeout or fatal error, please check your downloads directory and try again
```

**Comment by kylon** [comment]
mmh

comment all the lines where you see pbar in destreamer.js inside the for loop
```
//const pbar = new cliProgress.SingleBar({
//            barCompleteChar: '\u2588',
 //           barIncompleteChar: '\u2591',
 //           format: 'progress [{bar}] {percentage}% {speed} {eta_formatted}',
 //           barsize: Math.floor(process.stdout.columns / 3),
 //           stopOnComplete: true,
 //           hideCursor: true,
 //       });


// pbar.stop();


 //pbar.start(video.totalChunks, 0, {
//            speed: '0'
//        });


//pbar.update(currentChunks, {
 //               speed: data.bitrate
//            });


//pbar.stop();
```

rebuild, run with -v

**Comment by joao44289** [comment]
```
$ ./destreamer.sh -v -i "https://web.microsoftstream.com/video/fc7f80ea-e380-44db-8e2a-f34b64389a08?list=user&userId=82be014f-7d7f-4f3e-9079-d13113f1ade6"
Using ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers

Video URLs:
[
  'https://web.microsoftstream.com/video/fc7f80ea-e380-44db-8e2a-f34b64389a08?list=user&userId=82be014f-7d7f-4f3e-9079-d13113f1ade6'
]

Access token still good for 37 minutes.

Video GUIDs:
[ 'fc7f80ea-e380-44db-8e2a-f34b64389a08' ]
Fetching metadata...
Calling https://euno-1.api.microsoftstream.com/api/videos/fc7f80ea-e380-44db-8e2a-f34b64389a08?api-version=1.4-private
1
2
3
[ 'videos' ]
RangeError: Invalid array length
    at Object.parse (C:\destreamer\node_modules\cli-progress\lib\options.js:48:38)
    at new SingleBar (C:\destreamer\node_modules\cli-progress\lib\single-bar.js:8:24)
    at downloadVideo (C:\destreamer\build\src\destreamer.js:121:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


Unhandled error!
Timeout or fatal error, please check your downloads directory and try again
```

**Comment by kylon** [comment]
this make no sense, please attach your destreamer.ts

**Comment by joao44289** [comment]
[destreamer.zip](https://github.com/snobu/destreamer/files/4510538/destreamer.zip)

**Comment by kylon** [comment]
can you also attach destreamer.js in build/src?
are you sure the build was successful?

**Comment by joao44289** [comment]
Okay, I am very sorry but I just realized I was doing the changed to the wrong file. I was in the src folder not the build/src. I will try to add the lines now to the correct file.

**Comment by kylon** [comment]
the file was correct, you apply the changes in src folder

build/src is the file you obtain when you build
do all changes in src, not build/src

but i would like to see your build/src/destreamer.js because you still have a message that should not be there

**Comment by joao44289** [comment]
I added these lines to the destreamer.js on build/src

```
console.log(process.stdout.columns);
console.log(Math.floor(process.stdout.columns / 3));
console.log(i+" "+j+" "+l);
console.log(video.totalChunks)
```
And this was the log after building and running. I hope I did everything correctly and I'm sorry for wasting your time preciously.
```
$ ./destreamer.sh -v -i "https://web.microsoftstream.com/video/fc7f80ea-e380-44db-8e2a-f34b64389a08?list=user&userId=82be014f-7d7f-4f3e-9079-d13113f1ade6"
Using ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers

Video URLs:
[
  'https://web.microsoftstream.com/video/fc7f80ea-e380-44db-8e2a-f34b64389a08?list=user&userId=82be014f-7d7f-4f3e-9079-d13113f1ade6'
]

Access token still good for 49 minutes.

Video GUIDs:
[ 'fc7f80ea-e380-44db-8e2a-f34b64389a08' ]
Fetching metadata...
Calling https://euno-1.api.microsoftstream.com/api/videos/fc7f80ea-e380-44db-8e2a-f34b64389a08?api-version=1.4-private
[ 'videos' ]
RangeError: Invalid array length
    at Object.parse (C:\Users\Joao_\destreamer\node_modules\cli-progress\lib\options.js:48:38)
    at new SingleBar (C:\Users\Joao_\destreamer\node_modules\cli-progress\lib\single-bar.js:8:24)
    at downloadVideo (C:\Users\Joao_\destreamer\build\src\destreamer.js:121:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


Unhandled error!
Timeout or fatal error, please check your downloads directory and try again
```

**Comment by kylon** [comment]
no there is a misunderstanding, do all the changes in src folder

just attach build/src here

**Comment by joao44289** [comment]
[src.zip](https://github.com/snobu/destreamer/files/4510694/src.zip)

**Comment by kylon** [comment]
ok, something is wrong, your build is old
do all changes in src folder and run `npm run -s build` in destreamer root folder

destreamer.js in build/src should reflect the changes

**Comment by snobu** [comment]
I've never tested this in MINGW, can we move all testing to pure cmd.exe please so we don't introduce even more variables?

**Comment by kylon** [comment]
> I've never tested this in MINGW, can we move all testing to pure cmd.exe please so we don't introduce even more variables?

omg, missed that line o.o !

that could be the reason why cli-progress goes crazy, does it have a different terminal?

**Comment by joao44289** [comment]
@kylon @snobu I changed to cmd and it's working well now

**Comment by snobu** [comment]
Cool, @kylon i wonder if we can detect MINGW and throw a panic from init()

**Comment by kylon** [comment]
ninja'd lol, i was asking you the same
we need to kill mingw or change barsize calculation so that it does crash

i see no special platform in node for mingw
i would like to see the colum size of mingw terminal, maybe we can just fix that and everything will work

**Comment by snobu** [comment]
I'll just add a note to the readme for now.

**Comment by joao44289** [comment]
Just out of curiosity, any way of improving the download speed? Right now it's at 300kbits/s but my internet can do way more.

**Comment by snobu** [comment]
Yes, we're looking into ways to improve that, it's on our radar for sure.

**Comment by snobu** [comment]
Yes, we're looking into ways to improve that, it's on our radar for sure.
