### ISSUE TITLE
Module missing destreamer.js

### ISSUE THREAD

**Issue by Aknabacus** [snobu/destreamer#85]
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module 'C:\Users\Ahnaf Kabir\Downloads\destreamer-master\build\src\destreamer.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:862:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m
[90m    at internal/main/run_main_module.js:18:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by kylon** [comment]
Are you using cmd or powershell?
if no, please use one of them, this is not a destreamer issue

remember to delete the node_modules folder and install again with `npm i` and to rebuild destreamer with `npm run -s build`

**Comment by snobu** [comment]
I think he simply missed the build step. Everything is in the README, please don't ignore it.

**Comment by snobu** [comment]
Closing due to inactivity. @Aknabacus, feel free to reopen if necessary.

**Comment by Kaminate** [comment]
Yeah this happened to me too, I ran `npm install` but forgot to `npm run build`.
